#!/usr/bin/env python3
"""
generate-mock-seed.py — convert a golden raw JSON capture into a Tcl
seed file that openocd/lib/mock-openocd.tcl can source to pre-populate
its deterministic register/memory/coresight stubs.

Input:  reports/raw-<ts>.json  (or any captured raw JSON)
Output: a Tcl script that sets ::MOCK_REGS, ::MOCK_MEM, ::MOCK_AP_INFO,
        ::MOCK_A53, ::MOCK_BOOT_STATE, ::MOCK_VARIANT.

Used by tools/golden-test-roundtrip.sh to run enumerate.tcl offline
against a frozen register-value snapshot and verify the produced raw
JSON is byte-identical (modulo timestamp) to the golden.

Usage:
    python3 tools/generate-mock-seed.py tests/golden/zcu102-jtag-idle/raw.json \\
        > /tmp/mock-seed.tcl
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _tcl_escape(s: str) -> str:
    """Escape a string for Tcl braces. Braces themselves and backslashes
    need escaping; everything else is literal inside {...}."""
    return s.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def emit_seed(raw: dict, out) -> None:
    out.write("# Auto-generated by tools/generate-mock-seed.py.\n")
    out.write("# Sourced by openocd/lib/mock-openocd.tcl to seed the deterministic\n")
    out.write("# register store. Do not edit by hand.\n\n")

    # --- ::MOCK_REGS: addr_hex -> value_int ---
    out.write("set ::MOCK_REGS [dict create]\n")
    regs = raw.get("registers", {})
    for addr_hex, reg in regs.items():
        vi = reg.get("value_int")
        if vi is None:
            # ERR or missing — encode as -1 so the mock can distinguish
            continue
        out.write(f"dict set ::MOCK_REGS {addr_hex} {int(vi)}\n")

    # Some addresses are read via direct safe_rd (not dump_reg_qemu) and
    # therefore don't appear in registers{}. Seed those from semantic fields
    # in the JSON so the mock can satisfy reads of those addresses.
    #   - eFUSE DNA shadow: 0xFFCC100C / 1010 / 1014 → variant.device_dna_0/1/2
    dna_map = {
        "0xFFCC100C": raw.get("variant", {}).get("device_dna_0"),
        "0xFFCC1010": raw.get("variant", {}).get("device_dna_1"),
        "0xFFCC1014": raw.get("variant", {}).get("device_dna_2"),
    }

    def _to_int_local(v):
        if v is None:
            return None
        if isinstance(v, int):
            return v
        s = str(v).strip()
        if not s or s == "ERR":
            return None
        return int(s, 16) if s.lower().startswith("0x") else int(s, 10)

    for addr_hex, raw_v in dna_map.items():
        vi = _to_int_local(raw_v)
        if vi is not None:
            out.write(f"dict set ::MOCK_REGS {addr_hex} {vi}  ;# DNA from variant.device_dna_*\n")

    # CSU.IDCODE is captured to registers[] via the manual flow but at
    # 0xFFCA0040; ensure it's seeded even if registers[] entry is missing
    # for some reason (older capture format).
    if "0xFFCA0040" not in regs:
        variant = raw.get("variant", {})
        part_id = variant.get("part_id")
        rev = variant.get("silicon_rev")
        if part_id is not None and rev is not None:
            # Reconstruct: REVISION[31:28] | PART_ID[27:12] | MANUF_ID[11:1]=0x49 | CONST_1
            pi = _to_int_local(part_id) or 0
            rv = _to_int_local(rev) or 0
            idcode = ((rv & 0xF) << 28) | ((pi & 0xFFFF) << 12) | (0x49 << 1) | 1
            out.write(f"dict set ::MOCK_REGS 0xFFCA0040 {idcode}  ;# IDCODE reconstructed\n")
    out.write("\n")

    # --- ::MOCK_MEM: addr_hex -> { word0 word1 ... } ---
    # The raw capture stores per-block dumps under memory_probes only as
    # parsed single values, not full word arrays. The mock provides a
    # default-zero behavior; specific known regions (OCM bank0 start, etc.)
    # we seed from the variant + memory_probes data we have.
    out.write("set ::MOCK_MEM [dict create]\n")
    mp = raw.get("memory_probes", {})

    def _to_int(v):
        if v is None:
            return None
        if isinstance(v, int):
            return v
        s = str(v).strip()
        if not s:
            return None
        return int(s, 16) if s.lower().startswith("0x") else int(s, 10)

    def _flat_dict(v):
        """Some entries are stored as Tcl flat-dicts that round-trip to JSON
        as ['key1', 'val1', 'key2', 'val2', ...]. Parse those into a real dict.
        Returns None if v isn't a flat-dict-shaped list."""
        if isinstance(v, list) and len(v) % 2 == 0:
            return dict(zip(v[0::2], v[1::2]))
        return None

    for entry_key, fallback_addr_hex in (
        ("ocm_bank0_first", "0xFFFC0000"),
        ("ocm_alt_first",   "0xFFFE0000"),
    ):
        raw_v = mp.get(entry_key)
        flat = _flat_dict(raw_v)
        if flat:
            # Prefer the address embedded in the structured entry
            addr_hex = flat.get("address", fallback_addr_hex)
            word_v = _to_int(flat.get("first_word"))
        else:
            addr_hex = fallback_addr_hex
            word_v = _to_int(raw_v)
        if word_v is not None:
            out.write(f"dict set ::MOCK_MEM {addr_hex} [list {word_v}]\n")
    out.write("\n")

    # Direct safe_rd reads against fixed addresses that don't go through
    # dump_reg_qemu and don't show up in registers{} or the markdown scraper.
    # Map these from semantic memory_probes / boot_state entries to specific
    # register addresses so the mock returns the captured value.
    direct_reads = {
        "0xFFCA0050": _to_int(mp.get("csu_rom_digest_addr")),  # CSU.CSU_ROM_DIGEST_0 (audit C1: was 0xFFCA0048 which is reserved)
    }
    for addr_hex, vi in direct_reads.items():
        if vi is not None:
            out.write(f"dict set ::MOCK_REGS {addr_hex} {vi}  ;# from memory_probes\n")
    out.write("\n")

    # --- ::MOCK_AP_INFO: ap_num -> raw text ---
    out.write("set ::MOCK_AP_INFO [dict create]\n")
    cs = raw.get("coresight", {}).get("ap_info", {})
    for ap_num, text in cs.items():
        escaped = _tcl_escape(text)
        out.write(f"dict set ::MOCK_AP_INFO {ap_num} {{{escaped}}}\n")
    out.write("\n")

    # --- ::MOCK_A53 / boot_state / variant ---
    a53 = raw.get("a53", {})
    out.write("set ::MOCK_A53 [dict create]\n")
    for k, v in a53.items():
        if isinstance(v, bool):
            v_s = "1" if v else "0"
        elif isinstance(v, (int, str)):
            v_s = str(v)
        else:
            v_s = str(v)
        out.write(f"dict set ::MOCK_A53 {k} {{{_tcl_escape(v_s)}}}\n")
    out.write("\n")

    bs = raw.get("boot_state", {})
    out.write("set ::MOCK_BOOT_STATE [dict create]\n")
    for k, v in bs.items():
        out.write(f"dict set ::MOCK_BOOT_STATE {k} {{{_tcl_escape(str(v))}}}\n")
    out.write("\n")

    var = raw.get("variant", {})
    out.write("set ::MOCK_VARIANT [dict create]\n")
    for k, v in var.items():
        if isinstance(v, list):
            v_s = " ".join(str(x) for x in v)
        else:
            v_s = str(v)
        out.write(f"dict set ::MOCK_VARIANT {k} {{{_tcl_escape(v_s)}}}\n")
    out.write("\n")


_re = __import__("re")
# Two markdown patterns the script emits for an (addr, value) pair:
#
#   "X @ 0xADDR\`: \`0xVAL"        (eFUSE shadow loop, MASTER_ID slots — uses '@')
#   "X**: \`0xADDR = 0xVAL\`"      (dump_reg's say_kv — uses '=')
#
# Both patterns: address comes first, value comes second; both are hex.
# Value may be bare (`0x00001234`) or prefixed (`raw=0x00001234 ...`).
_MD_PATTERNS = [
    _re.compile(r"@\s*`?(0x[0-9a-fA-F]+)`?\*?\*?:\s*`(?:raw=)?(0x[0-9a-fA-F]+)"),
    _re.compile(r"`(0x[0-9a-fA-F]+)\s*=\s*(0x[0-9a-fA-F]+)`"),
]


def _scrape_md_extras(md_path: Path) -> list[tuple[str, int]]:
    """Pull (addr_hex, value_int) pairs from the paired enumerate.md.
    Captures direct safe_rd reads that don't go through dump_reg_qemu
    (eFUSE shadow, XPPU MASTER_ID slots, XPPU.POISON, etc.) so the mock
    returns the captured value for those addresses.

    Quietly tolerates a missing markdown file.
    """
    if not md_path.exists():
        return []
    out: list[tuple[str, int]] = []
    seen: set[str] = set()  # prefer first-seen value per address
    for line in md_path.read_text().splitlines():
        for pat in _MD_PATTERNS:
            m = pat.search(line)
            if not m:
                continue
            addr = "0x" + m.group(1)[2:].upper()
            if addr in seen:
                continue
            try:
                val = int(m.group(2), 16)
            except ValueError:
                continue
            out.append((addr, val))
            seen.add(addr)
            break  # one match per line
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("raw_json", type=Path,
                    help="Path to a raw enumeration JSON to seed the mock from")
    ap.add_argument("-o", "--output", type=Path, default=None,
                    help="Output Tcl file (default: stdout)")
    ap.add_argument("--md", type=Path, default=None,
                    help="Paired enumerate.md (default: derive from raw_json "
                         "name). Scraped for safe_rd-direct values that aren't "
                         "in registers{}.")
    args = ap.parse_args()
    if not args.raw_json.exists():
        print(f"ERROR: {args.raw_json} not found", file=sys.stderr)
        return 1
    raw = json.loads(args.raw_json.read_text())

    # Derive paired markdown path if not given (raw.json -> enumerate.md)
    md_path = args.md
    if md_path is None:
        stem = args.raw_json.stem
        if stem.startswith("raw"):
            md_name = stem.replace("raw", "enumerate", 1) + ".md"
            md_path = args.raw_json.parent / md_name
        elif stem == "raw":
            md_path = args.raw_json.parent / "enumerate.md"

    extras = _scrape_md_extras(md_path) if md_path else []

    def emit_with_extras(out):
        emit_seed(raw, out)
        if extras:
            out.write("# --- Extras scraped from enumerate.md "
                      "(safe_rd direct reads, no QEMU dict entry) ---\n")
            for addr_hex, val in extras:
                out.write(f"dict set ::MOCK_REGS {addr_hex} {val}\n")
            out.write("\n")

    if args.output:
        with args.output.open("w") as fh:
            emit_with_extras(fh)
        print(f"Wrote: {args.output} ({len(extras)} extras from "
              f"{md_path.name if md_path else 'no md'})", file=sys.stderr)
    else:
        emit_with_extras(sys.stdout)
    return 0


if __name__ == "__main__":
    sys.exit(main())
