#!/usr/bin/env python3
"""
qspi-make-patch.py — offline prep for openocd/qspi-write.tcl QW_OP=patch.

Reading a binary boot image inside OpenOCD's Jim Tcl is the documented binary-read gotcha
(reference_tcl_binary_read_bug). So we do the read-modify here, in Python, and emit a tiny Tcl data file
the writer `source`s — no binary I/O in Tcl. We extract the 4KB-subsector-aligned 8KB logical region around
the patch, apply the patch bytes, and split it into the per-die (dual-parallel) lower/upper 4KB halves
(even logical bytes -> lower die, odd -> upper).

Usage:
  python3 tools/qspi-make-patch.py dumps/boot-image.bin --offset 0x18da30 --hex 00008052c0035fd6 -o /tmp/qpatch.tcl
Then:
  QW_OP=patch QW_DATA=/tmp/qpatch.tcl openocd -f openocd/zcu102.cfg -c "init; source openocd/qspi-write.tcl; shutdown"
"""
import argparse

def main():
    ap = argparse.ArgumentParser(description="Prep a QSPI sub-sector patch for qspi-write.tcl.")
    ap.add_argument("image", help="the QSPI boot-image dump (logical bytes, == flash logical layout)")
    ap.add_argument("--offset", required=True, help="logical byte offset of the patch (hex or int)")
    ap.add_argument("--hex", required=True, help="patch bytes, e.g. 00008052c0035fd6")
    ap.add_argument("-o", "--out", required=True, help="output Tcl data file")
    a = ap.parse_args()

    off = int(a.offset, 0)
    pbytes = bytes.fromhex("".join(c for c in a.hex if c in "0123456789abcdefABCDEF"))
    SUB = 4096                       # per-die 4KB subsector
    pd_sub = (off >> 1) & ~0xFFF     # per-die 4KB-aligned subsector address
    log_base = pd_sub << 1           # logical base of the 8KB region (4KB/die)
    span = SUB * 2                   # 8192 logical bytes

    try:
        data = open(a.image, "rb").read()
    except OSError as e:
        raise SystemExit(f"error: cannot read {a.image!r}: {e}")
    if log_base + span > len(data):
        raise SystemExit(f"image too short: need 0x{log_base+span:x}, have 0x{len(data):x}")
    region = bytearray(data[log_base:log_base + span])

    # apply the patch
    rel = off - log_base
    region[rel:rel + len(pbytes)] = pbytes

    # split even->lower, odd->upper (each 4096 bytes)
    lo = region[0::2]
    up = region[1::2]
    assert len(lo) == SUB and len(up) == SUB

    def tcl_list(b):
        return " ".join("0x%02x" % x for x in b)

    with open(a.out, "w") as f:
        f.write(f"# generated by qspi-make-patch.py — patch 0x{off:x} = {a.hex}\n")
        f.write(f"set ::PD_SUB 0x{pd_sub:x}\n")
        f.write(f"set ::POFF   0x{off:x}\n")
        f.write(f"set ::PHEX   {a.hex}\n")
        f.write(f"set ::PLO {{{tcl_list(lo)}}}\n")
        f.write(f"set ::PUP {{{tcl_list(up)}}}\n")
    print(f"wrote {a.out}: per-die subsector 0x{pd_sub:x}, patch {len(pbytes)}B at logical 0x{off:x}")
    print(f"  region logical 0x{log_base:x}..0x{log_base+span:x}  (lower/upper {SUB}B each)")
    print(f"  sanity: lower[0:4] = {lo[:4].hex()}   (writer checks live flash == this before erasing)")

if __name__ == "__main__":
    main()
