#!/usr/bin/env python3
"""
vxworks-symtab.py — extract the embedded VxWorks symbol table from a raw kernel blob
(vxWorks.bin / a DRAM or QSPI-partition dump) and emit a Ghidra import script that names
every function, plus a plain address->name map.

Why this exists: the VxWorks kernel we recover is a stripped raw blob, not an ELF — but it
was built with a standalone symbol table (the one the shell's `lkup` uses). That table maps
~8k names to addresses, which is *better* than a bare ELF for reversing in Ghidra. This tool
turns it into Ghidra labels/functions.

Symbol-table entry layout (VxWorks 7, AArch64, observed):
    u64 chain        (hash-chain link; 0 at end)
    u64 namePtr      (link-VA pointer to the NUL-terminated name string)
    u64 value        (the symbol's address = link VA)
    u64 _pad
    u64 type         (e.g. 0x50000)
    u64 _pad
We don't assume a fixed stride or a flat array (it's a hash table) — we scan for the
namePtr/value pair pattern, which is robust to layout.

Link VA: the kernel is linked at a virtual address, not its physical load address. For the
ZCU102 VxWorks here, file offset 0 -> VA 0xFFFFFFFF80100000 (PA 0x100000 + the 0xFFFFFFFF80000000
VA/PA offset measured live via probe-phys-patch: pc 0xffffffff803ed870 -> virt2phys PA 0x3ed870).
Override with --va-base for a different image (derive it as: running_pc - virt2phys(pc) gives the
VA-PA offset; add the partition's destinationLoadAddress).

Usage:
    python3 tools/vxworks-symtab.py dumps/sd-extract/vxWorks.bin
    python3 tools/vxworks-symtab.py kernel.bin --va-base 0xffffffff80100000 \
        --out-ghidra vxworks_symbols.py --out-map vxworks_symbols.txt
Then in Ghidra: import vxWorks.bin as AARCH64:LE:64 at the --va-base, run the emitted script.
"""
import argparse
import struct
import sys
from pathlib import Path

DEFAULT_VA_BASE = 0xFFFFFFFF80100000
VA_LO = 0xFFFFFFFF80000000          # plausible kernel VA window (low)
VA_HI = 0xFFFFFFFF82000000          # ... and high bound (32 MB image headroom)


def _is_c_ident(b: bytes) -> bool:
    if not (1 <= len(b) <= 64):
        return False
    c0 = b[0:1]
    if not (c0.isalpha() or c0 == b"_"):
        return False
    return all(chr(c).isalnum() or chr(c) in "_$." for c in b)


def extract(data: bytes, va_base: int):
    """Return sorted list of (addr, name), deduped, by scanning for symtab entries."""
    n = len(data)
    end = n - 16
    syms = {}
    p = 0
    while p < end:
        name_va = struct.unpack_from("<Q", data, p)[0]
        # quick reject: a name pointer must land inside the image's VA range
        if VA_LO <= name_va < VA_HI:
            name_off = name_va - va_base
            if 0 <= name_off < n:
                z = data.find(b"\x00", name_off, min(name_off + 65, n))
                if z > name_off:
                    nm = data[name_off:z]
                    if _is_c_ident(nm):
                        value = struct.unpack_from("<Q", data, p + 8)[0]
                        if VA_LO <= value < VA_HI:
                            syms[value] = nm.decode("ascii", "replace")
        p += 4
    return sorted(syms.items())


def emit_ghidra(syms, path, va_base):
    """Write a self-contained Ghidra (Jython) script embedding the symbol list."""
    with open(path, "w") as f:
        f.write("# Auto-generated by vxworks-symtab.py — apply VxWorks symbols in Ghidra.\n")
        f.write("# Load vxWorks.bin as AARCH64:LE:64 at base 0x%016X, then run this script.\n" % va_base)
        f.write("# @category VxWorks\n")
        f.write("from ghidra.program.model.symbol import SourceType\n")
        f.write("fm = currentProgram.getFunctionManager()\n")
        f.write("st = currentProgram.getSymbolTable()\n")
        f.write("SYMS = [\n")
        for addr, name in syms:
            f.write("    (0x%X, %r),\n" % (addr, name))
        f.write("]\n")
        f.write(
            "created=0; labeled=0\n"
            "for addr_int, name in SYMS:\n"
            "    a = toAddr(addr_int)\n"
            "    try:\n"
            "        createLabel(a, name, True, SourceType.IMPORTED); labeled+=1\n"
            "    except Exception as e:\n"
            "        pass\n"
            "    if getInstructionAt(a) is None:\n"
            "        try: disassemble(a)\n"
            "        except: pass\n"
            "    if fm.getFunctionAt(a) is None:\n"
            "        try:\n"
            "            createFunction(a, name); created+=1\n"
            "        except: pass\n"
            "print('vxworks-symtab: labeled %d, functions %d of %d' % (labeled, created, len(SYMS)))\n"
        )


def main(argv=None):
    ap = argparse.ArgumentParser(description="Extract the VxWorks embedded symbol table -> Ghidra")
    ap.add_argument("image", help="raw VxWorks kernel blob (vxWorks.bin / dump)")
    ap.add_argument("--va-base", default=hex(DEFAULT_VA_BASE),
                    help="link VA of file offset 0 (default 0x%X)" % DEFAULT_VA_BASE)
    ap.add_argument("--out-ghidra", default="vxworks_symbols_ghidra.py",
                    help="Ghidra import script to write")
    ap.add_argument("--out-map", help="optional plain 'addr name' map to also write")
    ap.add_argument("--limit", type=int, default=20, help="how many samples to print")
    args = ap.parse_args(argv)

    va_base = int(args.va_base, 0)
    data = Path(args.image).read_bytes()
    syms = extract(data, va_base)
    if not syms:
        print("No symbol-table entries found. Wrong --va-base? "
              "(derive: running_pc - virt2phys(pc) = VA/PA offset; + load address)", file=sys.stderr)
        return 1

    emit_ghidra(syms, args.out_ghidra, va_base)
    if args.out_map:
        with open(args.out_map, "w") as f:
            for addr, name in syms:
                f.write("0x%016X %s\n" % (addr, name))

    print(f"VA base        : 0x{va_base:016X}")
    print(f"symbols found  : {len(syms)}")
    print(f"Ghidra script  : {args.out_ghidra}")
    if args.out_map:
        print(f"symbol map     : {args.out_map}")
    print("samples:")
    for addr, name in syms[:args.limit]:
        print(f"  0x{addr:016X}  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
